export const ACTION_STRING = {
    authLogin: "AUTH_LOGIN",
    authSignUp: "AUTH_SIGNUP",
    authForgot:"AUTH_FORGOT",
    getUserId:"GET_USER",
    searchReciver:"SEARCH_RECIVER",
    userTranfer:"USER_TRANSFER",
    setTransferParam: "SET_TRANSFER_PARAM",
    checkPin:'CHECK_PIN',
    getHistory:"GET_HISTORY",
    createTransfer:"CREATE_TRANSFER",
    topUp:"TOP_UP",
    pending: "_PENDING",
    fulfilled: "_FULFILLED",
    rejected: "_REJECTED",
  };