export const ACTION_STRING = {
    authLogin: "AUTH_LOGIN",
    authSignUp: "AUTH_SIGNUP",
    authForgot:"AUTH_FORGOT",
    getUserId:"GET_USER",
    searchReciver:"SEARCH_RECIVER",
    userTranfer:"USER_TRANSFER",
    setTransferParam: "SET_TRANSFER_PARAM",
    checkPin:'CHECK_PIN',
    downloadPdf:"DOWNLOAD_PDF",
    getHistory:"GET_HISTORY",
    updatePin:"UPDATE_PIN",
    getHistoryById:"GET_HISTORY_BY_ID",
    createTransfer:"CREATE_TRANSFER",
    changePassword:"CHANGE_PASSWORD",
    changePasswordEmail:"CHANGE_PASSWORD_EMAIL",
    getDashboard:"GET_DASHBOARD",
    updatePhone:"UPDATE_PHONE",
    updateImage:"UPDATE_IMAGE",
    updateName:"UPDATE_NAME",
    topUp:"TOP_UP",
    pending: "_PENDING",
    fulfilled: "_FULFILLED",
    rejected: "_REJECTED",
  };